name: Deploy Backend to Railway

on:
  push:
    branches: [ main, master ]
    paths: [ 'backend/**' ]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Test Backend
      run: |
        cd backend
        python -c "import server; print('Backend imports successfully')"
        
    - name: Create Railway Config
      run: |
        cat > railway.json << 'EOF'
        {
          "build": {
            "builder": "NIXPACKS"
          },
          "deploy": {
            "startCommand": "cd backend && python server.py",
            "healthcheckPath": "/",
            "healthcheckTimeout": 100,
            "restartPolicyType": "ON_FAILURE",
            "restartPolicyMaxRetries": 10
          }
        }
        EOF
        
        cat > Procfile << 'EOF'
        web: cd backend && python server.py
        EOF
        
        cat > requirements.txt << 'EOF'
        fastapi==0.110.1
        uvicorn==0.25.0
        boto3>=1.34.129
        requests-oauthlib>=2.0.0
        cryptography>=42.0.8
        python-dotenv>=1.0.1
        pymongo==4.5.0
        pydantic>=2.6.4
        email-validator>=2.2.0
        pyjwt>=2.10.1
        passlib>=1.7.4
        tzdata>=2024.2
        motor==3.3.1
        python-multipart>=0.0.9
        EOF
